import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import { Navbar } from "@/shared/components";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.className} h-full antialiased`}

    >
      <body className="relative w-full min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
