import type { Metadata } from "next";
import { Instrument_Sans, Cormorant_Garamond } from "next/font/google";
import { Navbar } from "@/shared/components";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"], 
  variable: "--font-serif"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${cormorantGaramond.variable} h-full antialiased`}

    >
      <body className="relative w-full min-h-full h-[200vh] flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
